// Body of a sum type, non-unit variant
logprob = { "logprob" ~ (sep+ ~ logprob_term)* }

logprob_term = {
    unconstrained_params
    | constrained_params
    | jacobian
}

unconstrained_params          = ${
    !("unconstrained_params" ~ (sep+ ~ "unconstrained_params" ~ (&sep | EOI))+)
    ~ "unconstrained_params" ~ ("=" ~ path)?
}
constrained_params          = ${
    !("constrained_params" ~ (sep+ ~ "constrained_params" ~ (&sep | EOI))+)
    ~ "constrained_params" ~ ("=" ~ path)?
}
